Add kalipi-tft support for hyperpixel 4

diff --git a/kalipi-tft-config/kalipi-tft-config b/kalipi-tft-config/kalipi-tft-config
--- a/kalipi-tft-config/kalipi-tft-config
+++ b/kalipi-tft-config/kalipi-tft-config
@@ -22,7 +22,7 @@ function print_version() {
 function do_update() {
     if [ ! "$INTERACTIVE" = True ]; then
         if [[ $EUID -ne 0 ]]; then
-            bail "re4son-pi-tft-setup must be run as root. try: sudo re4son-pi-tft-setup"
+            bail "kalipi-tft-config must be run as root. try: sudo re4son-pi-tft-setup"
         fi
     fi
     TEMP_FILE="/tmp/${BASE_NAME}"
@@ -100,6 +100,9 @@ function remove_tft() {
     if [ -e ${TARGET_HOMEDIR}/.60-libinput.conf.bak ]; then
         mv ${TARGET_HOMEDIR}/.60-libinput.conf.bak /usr/share/X11/xorg.conf.d/60-libinput.conf
     fi
+    systemctl stop hyperpixel4-init.service && systemctl disable hyperpixel4-init.service
+    # Do not delete hyperpixel4-init.service files so we can use them again
+    # Do not delete 15-i2c-modprobe.rules and i2cprobe as they may come in handy later
     if [ "$INTERACTIVE" = True ]; then
         if [ "$SILENT" = False ]; then 
             whiptail --msgbox "Touchscreen configuration successfully removed." 20 60
@@ -136,6 +139,7 @@ function print_help() {
     echo "                                             '4dpi'     (4D Systems 2.4\",3.2\" and 3.5\")"
     echo "                                             'elec22'   (Elecfreak 2.2\")"
     echo "                                             'hy28b'    (Hotmcu HY28B 2.8\")"
+    echo "                                             'hyper4t'  (HyperPixel touch 4.0\")"
     echo "                                             'jb35'     (JBTek 3.5\")"
     echo "                                             'kum35'    (Kuman 3.5\")"
     echo "                                             'kum35h'   (Kuman 3.5\" HDMI)"
@@ -1561,6 +1565,137 @@ EOF
     # update /boot/cmdline.txt
     info PI-TFT "Updating console to TFT..."
     ask_console
+
+    # resolve dependencies
+    info PI-TFT "Resolving dependencies..."
+    install_xserver-xorg-input-evdev
+
+    # success
+    do_setup_success
+
+    # reboot?
+    do_reboot
+
+    # Otherwise exit if not interactive
+    if [ ! "$INTERACTIVE" = True ]; then
+        exit 0
+    fi
+    
+}
+
+function do_install_hyper4t() {
+    # set framebuffer
+    FRAMEBUFFER="/dev/fb1"
+
+    # update /boot/config.txt
+    info PI-TFT "Updating /boot/config.txt..."
+    date=`date`
+    if [ "$ROTATION" = 180 ]; then
+        overlay="dtoverlay=hyperpixel4-touch:rotate"
+        rotate="display_rotate=1"
+    else
+        overlay="dtoverlay=hyperpixel4-touch"
+        rotate="display_rotate=3"
+    fi
+    cat >> /boot/config.txt <<EOF
+# --- added by re4son-pi-tft-setup $date ---
+dtparam=spi=on
+dtparam=i2c1=on
+dtparam=i2c_arm=on
+$overlay
+overscan_left=0
+overscan_right=0
+overscan_top=0
+overscan_bottom=0
+framebuffer_width=800
+framebuffer_height=480
+enable_dpi_lcd=1
+display_default_lcd=1
+dpi_group=2
+dpi_mode=87
+dpi_output_format=0x7f216
+$rotate
+hdmi_timings=480 0 10 16 59 800 0 15 113 15 0 0 0 60 0 32000000 6
+###########################################
+####  Overclocking the micro sdcard    ####
+#### Uncomment  84 for Raspberry Pi 2  ####
+# dtparam=sd_overclock=84
+#### Uncomment 100 for Raspberry Pi 3  ####
+# dtparam=sd_overclock=100
+###########################################
+# --- end re4son-pi-tft-setup $date ---
+EOF
+
+    # install hyperpixel4 init service
+    info PI-TFT "Installing HyperPixel 4 service"
+    if [ ! -f /usr/bin/hyperpixel4-init ]; then
+        wget -O /usr/bin/hyperpixel4-init https://github.com/pimoroni/hyperpixel4/raw/master/dist/hyperpixel4-init
+    fi
+    chmod 755 /usr/bin/hyperpixel4-init
+    if [ ! -f /etc/systemd/system/hyperpixel4-init.service ]; then
+        cat >> /etc/systemd/system/hyperpixel4-init.service <<EOF
+[Unit]
+Description=HyperPixel 4.0" LCD Display Initialization
+DefaultDependencies=no
+After=local-fs.target
+
+[Service]
+Type=oneshot
+ExecStart=/usr/bin/hyperpixel4-init
+
+[Install]
+WantedBy=multi-user.target
+EOF
+    fi
+    systemctl enable hyperpixel4-init.service
+    systemctl start hyperpixel4-init.service
+
+    # install Raspberry Pi udev workaround:
+    # The normal udev rule only looks up the i2c alias, so the compatible string would have to say "<something>,GDIX1001" and the distinction about which specific device is required would be lost.
+    # Raspbian uses a workaround: a custom shell command and a udev rule to run it. The shell command calls modprobe using the i2c alias, but if that fails it tries the device tree alias instead.
+    info PI-TFT "Installing udev rule 15-i2c-modprobe.rules for automatic detection"
+    if [ ! -f /usr/lib/kalipi-sys-mods/i2cprobe ]; then
+        mkdir -p /usr/lib/kalipi-sys-mods/
+        cat > /usr/lib/kalipi-sys-mods/i2cprobe <<EOF
+#!/bin/sh
+modprobe ${MODALIAS} || modprobe "of:N${OF_NAME}T<NULL>C\${OF_COMPATIBLE_0}"
+EOF
+
+    chmod 755 /usr/lib/kalipi-sys-mods/i2cprobe
+    fi
+
+    if [ ! -f /lib/udev/rules.d/15-i2c-modprobe.rules ]; then 
+        cat >> /lib/udev/rules.d/15-i2c-modprobe.rules <<EOF
+SUBSYSTEM=="i2c|spi", ENV{MODALIAS}=="?*", ENV{OF_NAME}=="?*", ENV{OF_COMPATIBLE_0}=="?*", RUN+="/usr/lib/kalipi-sys-mods/i2cprobe"
+EOF
+    fi
+
+    # moving /usr/share/X11/xorg.conf.d/99-fbturbo.conf
+    info PI-TFT "Removing X11 fbturbo.conf..."
+    update_fbturbo_conf
+
+    # update ~/.profile
+    info PI-TFT "Updating user profile..."
+    update_profile
+
+    # update /etc/pointercal
+    info PI-TFT "Updating TSLib default calibration..."
+    if [ "$ROTATION" = 0 ]; then
+        pointercal="107331 -724 1595748 -1133 37223 1482024 65536 800 480 0"
+    elif [ "$ROTATION" = 180 ]; then
+        pointercal="108299 -918 -190660 -408 38342 -381668 65536 800 480 0"
+    fi
+    cat > /etc/pointercal <<EOF
+$pointercal
+EOF
+
+    # update /etc/udev/rules.d/95-xxxxx.rules
+    info PI-TFT "Updating udev rules for Touchscreen..."
+    cat > /etc/udev/rules.d/95-stmpe.rules <<EOF
+SUBSYSTEM=="input", ATTRS{name}=="Goodix Capacitive TouchScreen", ENV{DEVNAME}=="*event*", SYMLINK+="input/touchscreen"
+EOF
+
+
 
     # resolve dependencies
     info PI-TFT "Resolving dependencies..."
@@ -4039,7 +4174,7 @@ function do_homedir_menu() {
 function do_rotation_menu() {
     def_item=$1
     calc_wt_size
-    ROT=$(whiptail --title "$def_item" --menu "Raspberry Touchscreen setup" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --default-item "$def_item" --ok-button Select --cancel-button Skip\
+    ROT=$(whiptail --title "$def_item" --menu "Raspberry Pi Touchscreen setup" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --default-item "$def_item" --ok-button Select --cancel-button Skip\
         "ROT000 0" "Do not rotate screen" \
         "ROT090 90" "Rotate screen by 90 degrees" \
         "ROT180 180" "Rotate screen by 180 degrees" \
@@ -4144,6 +4279,22 @@ function do_hotmcu_menu() {
     elif [ $RET -eq 0 ]; then
         case "$SCREEN" in
             hy28b*) do_rotation_menu "ROT090 90" && do_homedir_menu && do_confirm_menu $SCREEN ;;
+            *) whiptail --msgbox "Program error: unrecognized option" 20 60 1 ;;
+        esac || whiptail --msgbox "There was an error running option $SCREEN" 20 60 1
+    fi
+}
+
+function do_hyperpixel_menu() {
+    calc_wt_size
+    SCREEN=$(whiptail --title "$TITLE" --menu "HyperPixel Touchscreen setup" $WT_HEIGHT $WT_WIDTH $WT_MENU_HEIGHT --cancel-button Back --ok-button Select \
+        "hyper4t" "Pimoroni HyperPixel 4.0\" Touchscreen" \
+        3>&1 1>&2 2>&3)
+    RET=$?
+    if [ $RET -eq 1 ]; then
+        return 0
+    elif [ $RET -eq 0 ]; then
+        case "$SCREEN" in
+            hyper4t*) do_rotation_menu "ROT180 180" && do_homedir_menu && do_confirm_menu $SCREEN ;;
             *) whiptail --msgbox "Program error: unrecognized option" 20 60 1 ;;
         esac || whiptail --msgbox "There was an error running option $SCREEN" 20 60 1
     fi
@@ -4291,13 +4442,14 @@ function do_setup_menu() {
         "S030 Elecfreak" "Set up Elecfreak touchscreens" \
         "S040 Elecrow" "Set up Elecrow touchscreens" \
         "S050 Hotmcu" "Set up Hotmcu touchscreens" \
-        "S060 JBTek" "Set up JBTek touchscreens" \
-        "S070 KeDei" "Set up KeDei touchscreens" \
-        "S080 Kuman" "Set up Kuman touchscreens" \
-        "S090 Osoyoo" "Set up Osoyoo touchscreens" \
-        "S100 Raspberry Pi" "Set up original Raspberry Pi touchscreens" \
-        "S110 Sainsmart" "Set up Sainsmart touchscreens" \
-        "S120 Waveshare" "Set up Waveshare touchscreens" \
+        "S060 HyperPixel" "Set up HyperPixel touchscreens" \
+        "S070 JBTek" "Set up JBTek touchscreens" \
+        "S080 KeDei" "Set up KeDei touchscreens" \
+        "S090 Kuman" "Set up Kuman touchscreens" \
+        "S100 Osoyoo" "Set up Osoyoo touchscreens" \
+        "S110 Raspberry Pi" "Set up original Raspberry Pi touchscreens" \
+        "S120 Sainsmart" "Set up Sainsmart touchscreens" \
+        "S130 Waveshare" "Set up Waveshare touchscreens" \
     3>&1 1>&2 2>&3)
     RET=$?
     if [ $RET -eq 1 ]; then
@@ -4309,13 +4461,14 @@ function do_setup_menu() {
             S030\ *) do_elecfreak_menu;;
             S040\ *) do_elecrow_menu;;
             S050\ *) do_hotmcu_menu;;
-            S060\ *) do_jbtek_menu;;
-            S070\ *) do_kedei_menu;;
-            S080\ *) do_kuman_menu;;
-            S090\ *) do_osoyoo_menu;;
-            S100\ *) do_raspberry_menu;;
-            S110\ *) do_sainsmart_menu;;
-            S120\ *) do_waveshare_menu;;
+            S060\ *) do_hyperpixel_menu;;
+            S070\ *) do_jbtek_menu;;
+            S080\ *) do_kedei_menu;;
+            S090\ *) do_kuman_menu;;
+            S100\ *) do_osoyoo_menu;;
+            S110\ *) do_raspberry_menu;;
+            S120\ *) do_sainsmart_menu;;
+            S130\ *) do_waveshare_menu;;
             *) whiptail --msgbox "Program error: unrecognized option" 20 60 1 ;;
         esac || whiptail --msgbox "There was an error running option $FUN" 20 60 1
     fi
@@ -4355,6 +4508,16 @@ function do_show_config() {
     if [ -f "${TARGET_HOMEDIR}/.profile" ]; then
         local USRPROFILE=$(sed -n '/added by re4son-pi-tft-setup/,/end re4son-pi-tft-setup/p' "${TARGET_HOMEDIR}/.profile")
     fi
+    if [ -f "/etc/systemd/system/hyperpixel4-init.service" ]; then
+        local HPPXLINIT=$(cat "/etc/systemd/system/hyperpixel4-init.service")
+        local HPPXLINITSTAT=$(systemctl status hyperpixel4-init.service)
+    fi
+    if [ -f "/usr/lib/kalipi-sys-mods/i2cprobe" ]; then
+        local I2CPROBE=$(cat "/usr/lib/kalipi-sys-mods/i2cprobe")
+    fi
+    if [ -f "/lib/udev/rules.d/15-i2c-modprobe.rules" ]; then
+        local I2CRULES=$(cat "/lib/udev/rules.d/15-i2c-modprobe.rules")
+    fi  
     whiptail --title "Current Display Configuration" --scrolltext --msgbox "\
 
 /boot/cmdline.txt:
@@ -4386,6 +4549,18 @@ ${FBDEV}
 
 /etc/kbd/config:
 ${KBDCONF}
+
+/etc/systemd/system/hyperpixel4-init.service:
+${HPPXLINIT}
+
+Status hyperpixel4-init.service:
+${HPPXLINITSTAT}
+
+/usr/lib/kalipi-sys-mods/i2cprobe:
+${I2CPROBE}
+
+/lib/udev/rules.d/15-i2c-modprobe.rules
+${I2CRULES}
 
 ~/.profile:
 ${USRPROFILE}
@@ -4560,6 +4735,10 @@ case "${pitfttype}" in
 	hy28b)
 		ROTATION=90
                 do_install_hy28b
+		;;
+	hy28b)
+		ROTATION=0
+                do_install_hyper4t()
 		;;
 	jb35)
 		ROTATION=90
